import os

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QPropertyAnimation, QUrl, QTimer, pyqtSignal
from PyQt5.QtMultimedia import QMediaPlayer, QMediaContent
from PyQt5.QtTest import QTest
from PyQt5.QtWidgets import QMainWindow, QApplication, QGraphicsOpacityEffect

from NastrKompFormGG import Ui_NastrKompForm


class KompWindow(QMainWindow):
    window_closed = pyqtSignal()

    def __init__(self):
        super().__init__()



        self.PlStor = False

        self.setGeometry(0, 0, 1920, 1080)
        self.showFullScreen()

        self.setObjectName("Komp1Window")

        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("FonKomp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(1920, 1080))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1440, 0, 480, 991))
        self.label.setStyleSheet("background-color: rgb(51, 0, 77);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1440, 990, 481, 10))
        self.label_2.setStyleSheet("background-color: rgb(86, 21, 53);")
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(1450, 10, 461, 971))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(100, 225))
        self.pushButton_4.setStyleSheet("background-color: transparent;")
        self.pushButton_4.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Kart1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setIconSize(QtCore.QSize(149, 225))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(100, 225))
        self.pushButton_5.setStyleSheet("background-color: transparent;")
        self.pushButton_5.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Kart2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon2)
        self.pushButton_5.setIconSize(QtCore.QSize(149, 225))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 0, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(100, 225))
        self.pushButton_6.setStyleSheet("background-color: transparent;")
        self.pushButton_6.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Kart3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon3)
        self.pushButton_6.setIconSize(QtCore.QSize(149, 225))
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 0, 2, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_16.setMinimumSize(QtCore.QSize(100, 225))
        self.pushButton_16.setStyleSheet("background-color: transparent;")
        self.pushButton_16.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Kart4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_16.setIcon(icon4)
        self.pushButton_16.setIconSize(QtCore.QSize(149, 225))
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 1, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_7.setMinimumSize(QtCore.QSize(100, 225))
        self.pushButton_7.setStyleSheet("background-color: transparent;")
        self.pushButton_7.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Kart5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon5)
        self.pushButton_7.setIconSize(QtCore.QSize(149, 225))
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 1, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_8.setMinimumSize(QtCore.QSize(100, 225))
        self.pushButton_8.setStyleSheet("background-color: transparent;")
        self.pushButton_8.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Kart7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon6)
        self.pushButton_8.setIconSize(QtCore.QSize(149, 225))
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 2, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_10.setMinimumSize(QtCore.QSize(100, 225))
        self.pushButton_10.setStyleSheet("background-color: transparent;")
        self.pushButton_10.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Kart8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon7)
        self.pushButton_10.setIconSize(QtCore.QSize(149, 225))
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 2, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_11.setMinimumSize(QtCore.QSize(100, 225))
        self.pushButton_11.setStyleSheet("background-color: transparent;")
        self.pushButton_11.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Kart10.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon8)
        self.pushButton_11.setIconSize(QtCore.QSize(149, 225))
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 3, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_13.setMinimumSize(QtCore.QSize(100, 225))
        self.pushButton_13.setStyleSheet("background-color: transparent;")
        self.pushButton_13.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Kart11.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_13.setIcon(icon9)
        self.pushButton_13.setIconSize(QtCore.QSize(149, 225))
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 3, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_14.setMinimumSize(QtCore.QSize(100, 225))
        self.pushButton_14.setStyleSheet("background-color: transparent;")
        self.pushButton_14.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Kart12.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon10)
        self.pushButton_14.setIconSize(QtCore.QSize(149, 225))
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 3, 2, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_12.setMinimumSize(QtCore.QSize(100, 225))
        self.pushButton_12.setStyleSheet("background-color: transparent;")
        self.pushButton_12.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("Kart9.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon11)
        self.pushButton_12.setIconSize(QtCore.QSize(149, 225))
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 2, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_9.setMinimumSize(QtCore.QSize(100, 225))
        self.pushButton_9.setStyleSheet("background-color: transparent;")
        self.pushButton_9.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("Kart6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon12)
        self.pushButton_9.setIconSize(QtCore.QSize(149, 225))
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1439, 1000, 481, 81))
        self.label_5.setStyleSheet("\n"
"background-color: rgb(70, 7, 153);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1430, 0, 10, 1081))
        self.label_6.setStyleSheet("background-color: rgb(86, 21, 53);")
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1500, 1020, 61, 41))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(92, 107, 192);")
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1448, 1014, 48, 48))
        self.pushButton_2.setStyleSheet("background-color: transparent;")
        self.pushButton_2.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("kompManOsn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon13)
        self.pushButton_2.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1798, 1014, 48, 48))
        self.pushButton_3.setStyleSheet("background-color: transparent;")
        self.pushButton_3.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("KonpManVtor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon14)
        self.pushButton_3.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1850, 1020, 61, 41))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 137, 123);")
        self.label_4.setObjectName("label_4")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(1647, 1007, 66, 66))
        self.pushButton_15.setStyleSheet("background-color: transparent;")
        self.pushButton_15.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("KompObnPlan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_15.setIcon(icon15)
        self.pushButton_15.setIconSize(QtCore.QSize(66, 66))
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1440, 0, 480, 991))
        self.label_7.setStyleSheet("background-color: rgb(17, 6, 88);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(1450, 10, 461, 971))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_18 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_2.addWidget(self.pushButton_18, 0, 1, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_2.addWidget(self.pushButton_17, 0, 0, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_2.addWidget(self.pushButton_19, 1, 1, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_2.addWidget(self.pushButton_20, 1, 0, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_2.addWidget(self.pushButton_21, 2, 0, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_2.addWidget(self.pushButton_22, 2, 1, 1, 1)
        self.setCentralWidget(self.centralwidget)

        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 0, 301, 51))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(55, 36, 243, 100);\n"
                                   "color: rgb(248, 109, 54);\n"
                                   "border-radius: 6px;")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(1120, 1030, 301, 51))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setStyleSheet("background-color: rgb(55, 36, 243, 100);\n"
                                   "color: rgb(248, 109, 54);\n"
                                   "border-radius: 6px;")
        self.label_9.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(6, 1012, 64, 64))
        self.pushButton_23.setStyleSheet("background-color: transparent;")
        self.pushButton_23.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("KompNastrIc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_23.setIcon(icon16)
        self.pushButton_23.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_23.setObjectName("pushButton_23")

        fileeLLL = open("baza.txt", 'r', encoding='utf-8')
        self.logUs = fileeLLL.readlines()[-1]
        self.logUs = self.logUs.replace("\n", "")
        self.label_9.setText(self.logUs)
        fileeLLL.close()

        self.pushButton1_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1_2.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.pushButton1_2.setText("")
        self.pushButton1_2.setObjectName("pushButton")
        self.pushButton1_2.setStyleSheet("background-color: rgb(0, 0, 0);")

        self.V = 0
        self.Vm = 0

        self.player1 = QMediaPlayer()

        self.player1.setMedia(QMediaContent(QUrl(
            "ryanSound.mp3"
        )))

        self.player1.setVolume(1)

        self.player1.play()

        self.timer22 = QTimer(self)
        self.timer22.timeout.connect(self.fadeoutObr1)
        self.timer22.start(100)

        self.retranslateUi(self)
        self.SwapOsn()
        self.addFunction()

        self.KompPerexod1()

        QtCore.QMetaObject.connectSlotsByName(self)
        print(self.V)
        print(self.Vm)

    def addFunction(self):
        self.pushButton_15.clicked.connect(self.SwapOred)
        self.pushButton_23.clicked.connect(self.NastrKompFormOpen)

    def closeEvent(self, event):
        self.window_closed.emit()  # отправляем сигнал о закрытии окна А
        event.accept()

    def fadeoutObr1(self):
        current_volume = self.player1.volume()
        # Уменьшаем громкость на небольшое значение
        self.player1.setVolume(current_volume + 1)
        if current_volume >= 20:
            # Останавливаем таймер
            self.timer22.stop()

    def KompPerexod1(self):
        opacity_effect = QGraphicsOpacityEffect()
        self.pushButton1_2.setGraphicsEffect(opacity_effect)
        self.animation = QPropertyAnimation(opacity_effect, b"opacity")
        self.animation.setDuration(2500)  # Длительность анимации в миллисекундах
        self.animation.setStartValue(1.0)  # Начальное значение прозрачности (полностью непрозрачный)
        self.animation.setEndValue(0.0)  # Конечное значение прозрачности (полностью прозрачный)
        self.animation.start()
        QTest.qWait(2500)
        self.pushButton1_2.hide()

    def NastrKompFormOpen(self):
        self.nastr = Ui_NastrKompForm()
        self.nastr.exec()
        if self.nastr.ConcidVal == True:
            self.close()
            self.player1.stop()
            os.system("python formMenu2.py")

    def SwapOred(self):
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("KompObnPlan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("KompObnKart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        if self.PlStor == False:
            self.PlStor = True
            self.pushButton_15.setIcon(icon17)
            self.pushButton_15.setIconSize(QtCore.QSize(66, 66))
            self.SwapPlan()
        else:
            self.PlStor = False
            self.pushButton_15.setIcon(icon16)
            self.pushButton_15.setIconSize(QtCore.QSize(66, 66))
            self.SwapOsn()

    def SwapOsn(self):
        self.label_7.hide()
        self.pushButton_17.hide()
        self.pushButton_18.hide()
        self.pushButton_19.hide()
        self.pushButton_20.hide()
        self.pushButton_21.hide()
        self.pushButton_22.hide()
        self.label.show()
        self.pushButton_4.show()
        self.pushButton_5.show()
        self.pushButton_6.show()
        self.pushButton_7.show()
        self.pushButton_8.show()
        self.pushButton_9.show()
        self.pushButton_10.show()
        self.pushButton_11.show()
        self.pushButton_12.show()
        self.pushButton_13.show()
        self.pushButton_14.show()



    def SwapPlan(self):
        self.label_7.show()
        self.pushButton_17.show()
        self.pushButton_18.show()
        self.pushButton_19.show()
        self.pushButton_20.show()
        self.pushButton_21.show()
        self.pushButton_22.show()
        self.label.hide()
        self.pushButton_4.hide()
        self.pushButton_5.hide()
        self.pushButton_6.hide()
        self.pushButton_7.hide()
        self.pushButton_8.hide()
        self.pushButton_9.hide()
        self.pushButton_10.hide()
        self.pushButton_11.hide()
        self.pushButton_12.hide()
        self.pushButton_13.hide()
        self.pushButton_14.hide()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Komp1Window", "Komp1Window"))
        self.label_3.setText(_translate("MainWindow", "7777"))
        self.label_4.setText(_translate("MainWindow", "2228"))
        self.pushButton_18.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_17.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_19.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_20.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_21.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_22.setText(_translate("MainWindow", "PushButton"))
        self.label_8.setText(_translate("MainWindow", "Sokron"))


if __name__ == "__main__":
    import sys

    App = QApplication(sys.argv)
    window = KompWindow()
    window.show()
    App.exit(App.exec_())